"""Fix category_id to Integer

Revision ID: 7025059aa72f
Revises: e12c159086d0
Create Date: 2025-05-07 16:37:58.828275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7025059aa72f'
down_revision = 'e12c159086d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spendings', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spendings', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
